# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from comm.models import Device


def init_db(apps, div):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    esp = Device(id=1,deviceid="device-esp-001",platform="ESP8266",path="/dev/ttyUSB0:/dev/ttyUSB0")
    esp.save()
    esp1 = Device(id=2,deviceid="device-xia-001",platform="XiaomiSDJQR01RR",path="/dev/ttyUSB0:/dev/ttyUSB0")
    esp1.save()
    esp1 = Device(id=3,deviceid="device-ras-001",platform="RaspberryPi3",path="192.168.178.38")
    esp1.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleid', models.CharField(max_length=200)),
                ('modulename', models.CharField(max_length=200)),                
                ('containerid', models.CharField(max_length=200)),
                ('containertag', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=250)),
                ('platform', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='deviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.Device'),
        ),
         migrations.RunPython(init_db),
    ]
